# Generated by Django 2.0.4 on 2020-03-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlegrounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battlegrounds',
            options={'verbose_name': '酒馆战棋英雄数据', 'verbose_name_plural': '酒馆战棋英雄数据'},
        ),
        migrations.AddField(
            model_name='battlegrounds',
            name='final_placement_distribution',
            field=models.TextField(blank=True, default='', null=True, verbose_name='排名分布'),
        ),
        migrations.AddField(
            model_name='battlegrounds',
            name='min_mmr',
            field=models.IntegerField(default=0, verbose_name='样本最低分数'),
        ),
        migrations.AlterField(
            model_name='battlegrounds',
            name='mmr_range',
            field=models.CharField(choices=[('ALL', '所有玩家'), ('TOP_50_PERCENT', 'Top 50%'), ('TOP_20_PERCENT', 'Top 20%')], default='All', max_length=200, verbose_name='MMR Range'),
        ),
        migrations.AlterField(
            model_name='battlegrounds',
            name='tier',
            field=models.CharField(blank=True, choices=[('T1', '第一梯队'), ('T2', '第二梯队'), ('T3', '第三梯队'), ('T4', '第四梯队')], max_length=20, null=True, verbose_name='梯队'),
        ),
        migrations.AlterField(
            model_name='battlegrounds',
            name='time_frame',
            field=models.CharField(choices=[('LAST_7_DAYS', '最近7天'), ('CURRENT_PATCH', '当前版本')], default='Last7Days', max_length=200, verbose_name='时间范围'),
        ),
    ]
