# Generated by Django 2.0.4 on 2018-08-14 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HSRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, max_length=20, null=True, verbose_name='游戏模式')),
                ('index', models.IntegerField(default=-1, verbose_name='排名')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='职业')),
                ('winrate', models.CharField(blank=True, max_length=20, null=True, verbose_name='胜率')),
                ('report_time', models.DateField(default=datetime.datetime.now, verbose_name='日期')),
            ],
            options={
                'verbose_name': 'HS职业胜率排名',
                'verbose_name_plural': 'HS职业胜率排名',
            },
        ),
    ]
