# Generated by Django 2.0.4 on 2018-08-14 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsranking',
            name='index',
            field=models.IntegerField(verbose_name='排名'),
        ),
        migrations.AlterField(
            model_name='hsranking',
            name='mode',
            field=models.CharField(blank=True, choices=[('Standard', '标准模式'), ('Wild', '狂野模式'), ('Arena', '竞技场')], max_length=20, null=True, verbose_name='游戏模式'),
        ),
        migrations.AlterField(
            model_name='hsranking',
            name='name',
            field=models.CharField(blank=True, choices=[('Druid', '德鲁伊'), ('Hunter', '猎人'), ('Mage', '法师'), ('Paladin', '圣骑士'), ('Priest', '牧师'), ('Rogue', '潜行者'), ('Shaman', '萨满'), ('Warlock', '术士'), ('Warrior', '战士'), ('Neutral', '中立')], max_length=20, null=True, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='hsranking',
            name='report_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='日期'),
        ),
    ]
