# Generated by Django 2.0.4 on 2018-08-15 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_auto_20180814_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsranking',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='排名'),
        ),
        migrations.AlterField(
            model_name='hsranking',
            name='report_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='日期'),
        ),
    ]
