# Generated by Django 2.0.4 on 2018-08-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0003_auto_20180815_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hsranking',
            old_name='index',
            new_name='rank_no',
        ),
    ]
