# Generated by Django 2.0.4 on 2018-09-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0005_auto_20180824_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsranking',
            name='mode',
            field=models.CharField(blank=True, choices=[('All', '全部模式'), ('Standard', '标准模式'), ('Wild', '狂野模式'), ('Arena', '竞技场')], max_length=20, null=True, verbose_name='游戏模式'),
        ),
    ]
