# Generated by Django 2.0.4 on 2018-12-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0006_auto_20180917_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsranking',
            name='faction',
            field=models.CharField(blank=True, choices=[('Druid', '德鲁伊'), ('Hunter', '猎人'), ('Mage', '法师'), ('Paladin', '圣骑士'), ('Priest', '牧师'), ('Rogue', '潜行者'), ('Shaman', '萨满'), ('Warlock', '术士'), ('Warrior', '战士'), ('Neutral', '中立')], max_length=100, null=True, verbose_name='职业'),
        ),
        migrations.AddField(
            model_name='hsranking',
            name='game_type',
            field=models.CharField(blank=True, choices=[('All', '全部模式'), ('Standard', '标准模式'), ('Wild', '狂野模式'), ('Arena', '竞技场')], max_length=20, null=True, verbose_name='游戏模式'),
        ),
        migrations.AddField(
            model_name='hsranking',
            name='popularity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='热度'),
        ),
        migrations.AddField(
            model_name='hsranking',
            name='total_games',
            field=models.IntegerField(blank=True, null=True, verbose_name='总对局数'),
        ),
        migrations.AddField(
            model_name='hsranking',
            name='win_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='胜率'),
        ),
    ]
