# Generated by Django 2.0.4 on 2018-12-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0007_auto_20181213_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsranking',
            name='popularity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='热度'),
        ),
        migrations.AlterField(
            model_name='hsranking',
            name='win_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='胜率'),
        ),
    ]
