# Generated by Django 2.0.4 on 2018-12-18 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0008_auto_20181213_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hsranking',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='hsranking',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hsranking',
            name='rank_no',
        ),
        migrations.RemoveField(
            model_name='hsranking',
            name='winrate',
        ),
    ]
