# Generated by Django 2.2 on 2021-03-27 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0011_auto_20200410_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsranking',
            name='game_type',
            field=models.CharField(blank=True, choices=[('All', '全部模式'), ('Classic', '经典模式'), ('Standard', '标准模式'), ('Wild', '狂野模式'), ('Arena', '竞技场'), ('Duels', '对决模式')], max_length=20, null=True, verbose_name='游戏模式'),
        ),
        migrations.AlterField(
            model_name='hsranking',
            name='report_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='日期'),
        ),
    ]
