# Generated by Django 2.0.4 on 2018-08-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_auto_20180818_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decks',
            name='background_img',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='背景图'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='clazzCount',
            field=models.TextField(blank=True, null=True, verbose_name='类别组成'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='deck_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='卡组ID'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='deck_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='套牌名称'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='对局时长'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='dust_cost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='合成花费'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='faction',
            field=models.CharField(blank=True, choices=[('Druid', '德鲁伊'), ('Hunter', '猎人'), ('Mage', '法师'), ('Paladin', '圣骑士'), ('Priest', '牧师'), ('Rogue', '潜行者'), ('Shaman', '萨满'), ('Warlock', '术士'), ('Warrior', '战士'), ('Neutral', '中立')], max_length=20, null=True, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='faction_win_rate',
            field=models.TextField(blank=True, null=True, verbose_name='各职业对战胜率'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='game_count',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='总对局数'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='rarityCount',
            field=models.TextField(blank=True, null=True, verbose_name='费用统计'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='statistic',
            field=models.TextField(blank=True, null=True, verbose_name='费用统计'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='turns',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='回合数'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='win_rate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='胜率'),
        ),
    ]
