# Generated by Django 2.0.4 on 2018-08-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_auto_20180818_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decks',
            name='clazzCount',
            field=models.TextField(blank=True, default={}, null=True, verbose_name='类别组成'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='对局时长'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='faction_win_rate',
            field=models.TextField(blank=True, default={}, null=True, verbose_name='各职业对战胜率'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='game_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='总对局数'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='rarityCount',
            field=models.TextField(blank=True, default={}, null=True, verbose_name='费用统计'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='statistic',
            field=models.TextField(blank=True, default={}, null=True, verbose_name='费用统计'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='turns',
            field=models.IntegerField(blank=True, null=True, verbose_name='回合数'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='win_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='胜率'),
        ),
    ]
