# Generated by Django 2.0.4 on 2018-08-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_auto_20180818_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decks',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='对局时长'),
        ),
    ]
