# Generated by Django 2.0.4 on 2018-08-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0006_auto_20180818_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decks',
            name='card_list',
            field=models.TextField(blank=True, default='', null=True, verbose_name='卡组套牌'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='clazzCount',
            field=models.TextField(blank=True, default='', null=True, verbose_name='类别组成'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='faction_win_rate',
            field=models.TextField(blank=True, default='', null=True, verbose_name='各职业对战胜率'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='rarityCount',
            field=models.TextField(blank=True, default='', null=True, verbose_name='费用统计'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='statistic',
            field=models.TextField(blank=True, default='', null=True, verbose_name='费用统计'),
        ),
    ]
