# Generated by Django 2.0.4 on 2018-08-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0007_auto_20180818_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decks',
            name='rarityCount',
            field=models.TextField(blank=True, default='', null=True, verbose_name='稀有统计'),
        ),
    ]
