# Generated by Django 2.0.4 on 2018-08-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0008_auto_20180821_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decks',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='对局时长'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='win_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='胜率'),
        ),
    ]
