# Generated by Django 2.0.4 on 2018-09-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0011_auto_20180824_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='decks',
            name='deck_code',
            field=models.TextField(blank=True, default='', null=True, verbose_name='卡组代码'),
        ),
    ]
