# Generated by Django 2.0.4 on 2018-09-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0012_decks_deck_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decks',
            name='turns',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='回合数'),
        ),
    ]
