# Generated by Django 2.0.4 on 2018-09-28 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0014_decks_trending_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='卡组ID')),
                ('faction', models.CharField(blank=True, choices=[('Druid', '德鲁伊'), ('Hunter', '猎人'), ('Mage', '法师'), ('Paladin', '圣骑士'), ('Priest', '牧师'), ('Rogue', '潜行者'), ('Shaman', '萨满'), ('Warlock', '术士'), ('Warrior', '战士'), ('Neutral', '中立')], max_length=20, null=True, verbose_name='职业')),
                ('deck_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='套牌名称')),
                ('dust_cost', models.CharField(blank=True, max_length=100, null=True, verbose_name='合成花费')),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='胜率')),
                ('game_count', models.IntegerField(blank=True, null=True, verbose_name='总对局数')),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='对局时长')),
                ('background_img', models.CharField(blank=True, max_length=200, null=True, verbose_name='背景图')),
                ('card_list', models.TextField(blank=True, default='', null=True, verbose_name='卡组套牌')),
                ('deck_code', models.TextField(blank=True, default='', null=True, verbose_name='卡组代码')),
                ('clazzCount', models.TextField(blank=True, default='', null=True, verbose_name='类别组成')),
                ('rarityCount', models.TextField(blank=True, default='', null=True, verbose_name='稀有统计')),
                ('statistic', models.TextField(blank=True, default='', null=True, verbose_name='费用统计')),
                ('turns', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='回合数')),
                ('faction_win_rate', models.TextField(blank=True, default='', null=True, verbose_name='各职业对战胜率')),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='日期')),
            ],
            options={
                'verbose_name': '48小时流行卡组',
                'verbose_name_plural': '48小时流行卡组',
            },
        ),
        migrations.RemoveField(
            model_name='decks',
            name='trending_flag',
        ),
    ]
