# Generated by Django 2.0.4 on 2018-10-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0015_auto_20180928_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='decks',
            name='real_game_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='实际对局数'),
        ),
        migrations.AddField(
            model_name='trending',
            name='real_game_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='实际对局数'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='game_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='对局数'),
        ),
    ]
