# Generated by Django 2.0.4 on 2018-10-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0017_auto_20181014_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='dust_cost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='合成花费'),
        ),
    ]
