# Generated by Django 2.0.4 on 2018-10-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0018_auto_20181014_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='decks',
            name='mode',
            field=models.CharField(blank=True, choices=[('Standard', '标准模式'), ('Wild', '狂野模式')], default='Standard', help_text='游戏模式', max_length=20, null=True, verbose_name='游戏模式'),
        ),
    ]
