# Generated by Django 2.0.4 on 2019-09-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0020_auto_20181025_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='mulligan',
            field=models.TextField(blank=True, default='', null=True, verbose_name='调度建议'),
        ),
    ]
