# Generated by Django 2.2 on 2020-12-06 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0024_auto_20201204_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='decks',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加日期'),
        ),
    ]
