# Generated by Django 2.2 on 2020-12-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0025_auto_20201206_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='decks',
            name='mulligan',
            field=models.TextField(blank=True, default='', null=True, verbose_name='调度建议'),
        ),
    ]
