# Generated by Django 2.2 on 2020-12-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0026_decks_mulligan'),
    ]

    operations = [
        migrations.AddField(
            model_name='decks',
            name='card_array',
            field=models.TextField(blank=True, default='', null=True, verbose_name='包含单卡'),
        ),
    ]
