# Generated by Django 2.2 on 2021-07-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0028_auto_20201208_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decks',
            name='mode',
            field=models.CharField(blank=True, choices=[('Standard', '标准模式'), ('Wild', '狂野模式'), ('Classic', '经典模式')], default='Standard', max_length=20, null=True, verbose_name='游戏模式'),
        ),
    ]
