# Generated by Django 2.0.4 on 2018-08-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20180810_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='standard',
            field=models.NullBooleanField(verbose_name='标准模式'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='wild',
            field=models.NullBooleanField(verbose_name='狂野模式'),
        ),
    ]
