# Generated by Django 2.0.4 on 2018-08-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20180810_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='wild',
        ),
        migrations.AddField(
            model_name='cards',
            name='mode',
            field=models.CharField(blank=True, choices=[('Standard', '标准模式'), ('Wild', '狂野模式')], help_text='游戏模式', max_length=20, null=True, verbose_name='游戏模式'),
        ),
    ]
