# Generated by Django 2.0.4 on 2018-08-11 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20180810_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(default='', max_length=20, verbose_name='扩展包（中文）')),
                ('ename', models.CharField(default='', max_length=20, verbose_name='扩展包（英文）')),
                ('image', models.ImageField(max_length=200, upload_to='series/', verbose_name='扩展包Logo')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '扩展包名',
                'verbose_name_plural': '扩展包名',
            },
        ),
        migrations.RemoveField(
            model_name='cards',
            name='seriesAbbr',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='seriesName',
        ),
        migrations.AlterField(
            model_name='cards',
            name='faction',
            field=models.CharField(choices=[('Druid', '德鲁伊'), ('Hunter', '猎人'), ('Mage', '法师'), ('Paladin', '圣骑士'), ('Priest', '牧师'), ('Rogue', '潜行者'), ('Shaman', '萨满'), ('Warlock', '术士'), ('Warrior', '战士'), ('Neutral', '中立')], default='', max_length=20, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='rarity',
            field=models.CharField(choices=[('1', '基本'), ('2', '普通'), ('3', '稀有'), ('4', '史诗'), ('5', '传说')], default='', max_length=20, verbose_name='稀有度'),
        ),
        migrations.AddField(
            model_name='cards',
            name='series',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='cards', to='cards.Series', verbose_name='扩展包系列'),
        ),
    ]
