# Generated by Django 2.0.4 on 2018-08-12 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20180811_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': '扩展包', 'verbose_name_plural': '扩展包'},
        ),
        migrations.AlterField(
            model_name='cards',
            name='clazz',
            field=models.CharField(blank=True, choices=[('1', '随从'), ('2', '法术'), ('3', '装备'), ('4', '英雄牌')], max_length=20, null=True, verbose_name='卡牌类别'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='ename',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='英文名'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='faction',
            field=models.CharField(blank=True, choices=[('Druid', '德鲁伊'), ('Hunter', '猎人'), ('Mage', '法师'), ('Paladin', '圣骑士'), ('Priest', '牧师'), ('Rogue', '潜行者'), ('Shaman', '萨满'), ('Warlock', '术士'), ('Warrior', '战士'), ('Neutral', '中立')], max_length=20, null=True, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='race',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='种族'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='rarity',
            field=models.CharField(blank=True, choices=[('1', '基本'), ('2', '普通'), ('3', '稀有'), ('4', '史诗'), ('5', '传说')], max_length=20, null=True, verbose_name='稀有度'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='rule',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='卡牌效果说明'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='cards.Series', verbose_name='扩展包系列'),
        ),
    ]
