# Generated by Django 2.0.4 on 2018-08-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20180812_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='mode',
            field=models.CharField(blank=True, choices=[('Standard', '标准模式'), ('Wild', '狂野模式'), ('Arena', '竞技场')], help_text='游戏模式', max_length=20, null=True, verbose_name='游戏模式'),
        ),
    ]
