# Generated by Django 2.0.4 on 2018-09-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_auto_20180814_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSCards',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='id')),
                ('dbfId', models.IntegerField(verbose_name='DBF IDs')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('cost', models.IntegerField(verbose_name='费用')),
                ('attack', models.IntegerField(blank=True, null=True, verbose_name='攻击')),
                ('health', models.IntegerField(blank=True, null=True, verbose_name='血量')),
                ('cardClass', models.CharField(blank=True, choices=[('Druid', '德鲁伊'), ('Hunter', '猎人'), ('Mage', '法师'), ('Paladin', '圣骑士'), ('Priest', '牧师'), ('Rogue', '潜行者'), ('Shaman', '萨满'), ('Warlock', '术士'), ('Warrior', '战士'), ('Neutral', '中立')], max_length=20, null=True, verbose_name='职业')),
                ('rarity', models.CharField(choices=[('FREE', '免费'), ('COMMON', '普通'), ('RARE', '稀有'), ('EPIC', '史诗'), ('LEGENDARY', '传说')], max_length=20, verbose_name='稀有度')),
                ('type', models.CharField(blank=True, choices=[('MINION', '随从'), ('SPELL', '法术'), ('WEAPON', '武器'), ('HERO', '英雄牌')], max_length=20, null=True, verbose_name='卡牌类别')),
                ('mechanics', models.CharField(blank=True, max_length=20, null=True, verbose_name='卡牌机制')),
                ('flavor', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('text', models.TextField(blank=True, null=True, verbose_name='效果')),
                ('artist', models.CharField(blank=True, max_length=20, null=True, verbose_name='艺术家')),
                ('collectible', models.BooleanField(verbose_name='可收集')),
                ('set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HSCards', to='cards.Series', verbose_name='扩展包系列')),
            ],
            options={
                'verbose_name': '卡牌详情',
                'verbose_name_plural': '卡牌详情',
            },
        ),
        migrations.AlterField(
            model_name='cards',
            name='clazz',
            field=models.CharField(blank=True, choices=[('MINION', '随从'), ('SPELL', '法术'), ('WEAPON', '武器'), ('HERO', '英雄牌')], max_length=20, null=True, verbose_name='卡牌类别'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='rarity',
            field=models.CharField(blank=True, choices=[('FREE', '免费'), ('COMMON', '普通'), ('RARE', '稀有'), ('EPIC', '史诗'), ('LEGENDARY', '传说')], max_length=20, null=True, verbose_name='稀有度'),
        ),
    ]
