# Generated by Django 2.0.4 on 2018-09-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_auto_20180902_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscards',
            name='artist',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='艺术家'),
        ),
        migrations.AlterField(
            model_name='hscards',
            name='mechanics',
            field=models.TextField(blank=True, null=True, verbose_name='卡牌机制'),
        ),
    ]
