# Generated by Django 2.0.4 on 2018-09-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_auto_20180902_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscards',
            name='race',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='种族'),
        ),
    ]
