# Generated by Django 2.0.4 on 2018-09-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_auto_20180902_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscards',
            name='ename',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='英文名'),
        ),
        migrations.AlterField(
            model_name='hscards',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
    ]
