# Generated by Django 2.0.4 on 2018-11-11 15:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_auto_20180917_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsId', models.CharField(blank=True, max_length=20, null=True, verbose_name='hsId')),
                ('dbfId', models.IntegerField(verbose_name='DBF IDs')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('ename', models.CharField(blank=True, max_length=100, null=True, verbose_name='英文名')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='费用')),
                ('attack', models.IntegerField(blank=True, null=True, verbose_name='攻击')),
                ('health', models.IntegerField(blank=True, null=True, verbose_name='血量')),
                ('cardClass', models.CharField(blank=True, choices=[('Druid', '德鲁伊'), ('Hunter', '猎人'), ('Mage', '法师'), ('Paladin', '圣骑士'), ('Priest', '牧师'), ('Rogue', '潜行者'), ('Shaman', '萨满'), ('Warlock', '术士'), ('Warrior', '战士'), ('Neutral', '中立')], max_length=20, null=True, verbose_name='职业')),
                ('race', models.CharField(blank=True, max_length=20, null=True, verbose_name='种族')),
                ('rarity', models.CharField(choices=[('FREE', '免费'), ('COMMON', '普通'), ('RARE', '稀有'), ('EPIC', '史诗'), ('LEGENDARY', '传说')], max_length=20, verbose_name='稀有度')),
                ('type', models.CharField(blank=True, choices=[('MINION', '随从'), ('SPELL', '法术'), ('WEAPON', '武器'), ('HERO', '英雄牌')], max_length=20, null=True, verbose_name='卡牌类别')),
                ('mechanics', models.TextField(blank=True, null=True, verbose_name='卡牌机制')),
                ('flavor', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('text', models.TextField(blank=True, null=True, verbose_name='效果')),
                ('artist', models.CharField(blank=True, max_length=200, null=True, verbose_name='艺术家')),
                ('collectible', models.BooleanField(verbose_name='可收集')),
                ('classification', models.CharField(choices=[('ALL', '全部'), ('DRUID', '德鲁伊'), ('HUNTER', '猎人'), ('MAGE', '法师'), ('PALADIN', '圣骑士'), ('PRIEST', '牧师'), ('ROGUE', '潜行者'), ('SHAMAN', '萨满'), ('WARLOCK', '术士'), ('WARRIOR', '战士')], max_length=20, verbose_name='职业分类')),
                ('times_played', models.IntegerField(blank=True, null=True, verbose_name='打出次数')),
                ('played_pop', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='打出卡牌中占比')),
                ('played_winrate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='打出胜率')),
                ('deck_pop', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='套牌中出现概率')),
                ('deck_winrate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='卡组胜率')),
                ('copies', models.IntegerField(blank=True, null=True, verbose_name='张数')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ArenaCards', to='cards.Series', verbose_name='扩展包系列')),
            ],
            options={
                'verbose_name': '竞技场单卡数据',
                'verbose_name_plural': '竞技场单卡数据',
            },
        ),
    ]
