# Generated by Django 2.0.4 on 2018-11-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0020_arenacards'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscards',
            name='audio_attack_en',
            field=models.TextField(blank=True, null=True, verbose_name='攻击音效（英）'),
        ),
        migrations.AddField(
            model_name='hscards',
            name='audio_attack_zh',
            field=models.TextField(blank=True, null=True, verbose_name='攻击音效（中）'),
        ),
        migrations.AddField(
            model_name='hscards',
            name='audio_death_en',
            field=models.TextField(blank=True, null=True, verbose_name='阵亡音效（英）'),
        ),
        migrations.AddField(
            model_name='hscards',
            name='audio_death_zh',
            field=models.TextField(blank=True, null=True, verbose_name='阵亡音效（中）'),
        ),
        migrations.AddField(
            model_name='hscards',
            name='audio_play_en',
            field=models.TextField(blank=True, null=True, verbose_name='入场音效（英）'),
        ),
        migrations.AddField(
            model_name='hscards',
            name='audio_play_zh',
            field=models.TextField(blank=True, null=True, verbose_name='入场音效（中）'),
        ),
    ]
