# Generated by Django 2.0.4 on 2018-11-09 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0020_arenacards'),
    ]

    operations = [
        migrations.AddField(
            model_name='arenacards',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
    ]
