# Generated by Django 2.0.4 on 2018-11-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0022_auto_20181125_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscards',
            name='audio_trigger_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='效果触发音效（英）'),
        ),
        migrations.AddField(
            model_name='hscards',
            name='audio_trigger_zh',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='效果触发音效（中）'),
        ),
    ]
