# Generated by Django 2.0.4 on 2018-11-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0023_auto_20181126_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscards',
            name='audio_attack_en',
            field=models.TextField(blank=True, null=True, verbose_name='攻击音效（英）'),
        ),
        migrations.AlterField(
            model_name='hscards',
            name='audio_attack_zh',
            field=models.TextField(blank=True, null=True, verbose_name='攻击音效（中）'),
        ),
        migrations.AlterField(
            model_name='hscards',
            name='audio_death_en',
            field=models.TextField(blank=True, null=True, verbose_name='阵亡音效（英）'),
        ),
        migrations.AlterField(
            model_name='hscards',
            name='audio_death_zh',
            field=models.TextField(blank=True, null=True, verbose_name='阵亡音效（中）'),
        ),
        migrations.AlterField(
            model_name='hscards',
            name='audio_play_en',
            field=models.TextField(blank=True, null=True, verbose_name='入场音效（英）'),
        ),
        migrations.AlterField(
            model_name='hscards',
            name='audio_play_zh',
            field=models.TextField(blank=True, null=True, verbose_name='入场音效（中）'),
        ),
        migrations.AlterField(
            model_name='hscards',
            name='audio_trigger_en',
            field=models.TextField(blank=True, null=True, verbose_name='效果触发音效（英）'),
        ),
        migrations.AlterField(
            model_name='hscards',
            name='audio_trigger_zh',
            field=models.TextField(blank=True, null=True, verbose_name='效果触发音效（中）'),
        ),
    ]
