# Generated by Django 2.0.4 on 2018-12-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0024_auto_20181129_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscards',
            name='eflavor',
            field=models.TextField(blank=True, null=True, verbose_name='英文描述'),
        ),
    ]
