# Generated by Django 2.0.4 on 2018-12-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0025_hscards_eflavor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arenacards',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='arenacards',
            name='copies',
        ),
        migrations.RemoveField(
            model_name='arenacards',
            name='deck_pop',
        ),
        migrations.RemoveField(
            model_name='arenacards',
            name='deck_winrate',
        ),
        migrations.RemoveField(
            model_name='arenacards',
            name='played_pop',
        ),
        migrations.RemoveField(
            model_name='arenacards',
            name='played_winrate',
        ),
        migrations.RemoveField(
            model_name='arenacards',
            name='times_played',
        ),
        migrations.AddField(
            model_name='arenacards',
            name='class_all',
            field=models.TextField(blank=True, null=True, verbose_name='全部职业'),
        ),
        migrations.AddField(
            model_name='arenacards',
            name='class_druid',
            field=models.TextField(blank=True, null=True, verbose_name='德鲁伊'),
        ),
        migrations.AddField(
            model_name='arenacards',
            name='class_hunter',
            field=models.TextField(blank=True, null=True, verbose_name='猎人'),
        ),
        migrations.AddField(
            model_name='arenacards',
            name='class_mage',
            field=models.TextField(blank=True, null=True, verbose_name='法师'),
        ),
        migrations.AddField(
            model_name='arenacards',
            name='class_paladin',
            field=models.TextField(blank=True, null=True, verbose_name='圣骑士'),
        ),
        migrations.AddField(
            model_name='arenacards',
            name='class_priest',
            field=models.TextField(blank=True, null=True, verbose_name='牧师'),
        ),
        migrations.AddField(
            model_name='arenacards',
            name='class_rogue',
            field=models.TextField(blank=True, null=True, verbose_name='潜行者'),
        ),
        migrations.AddField(
            model_name='arenacards',
            name='class_shaman',
            field=models.TextField(blank=True, null=True, verbose_name='萨满'),
        ),
        migrations.AddField(
            model_name='arenacards',
            name='class_warlock',
            field=models.TextField(blank=True, null=True, verbose_name='术士'),
        ),
        migrations.AddField(
            model_name='arenacards',
            name='class_warrior',
            field=models.TextField(blank=True, null=True, verbose_name='战士'),
        ),
    ]
