# Generated by Django 2.0.4 on 2018-12-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0026_auto_20181212_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arenacards',
            name='class_all',
        ),
        migrations.RemoveField(
            model_name='arenacards',
            name='class_druid',
        ),
        migrations.RemoveField(
            model_name='arenacards',
            name='class_hunter',
        ),
        migrations.RemoveField(
            model_name='arenacards',
            name='class_mage',
        ),
        migrations.RemoveField(
            model_name='arenacards',
            name='class_paladin',
        ),
        migrations.RemoveField(
            model_name='arenacards',
            name='class_priest',
        ),
        migrations.RemoveField(
            model_name='arenacards',
            name='class_rogue',
        ),
        migrations.RemoveField(
            model_name='arenacards',
            name='class_shaman',
        ),
        migrations.RemoveField(
            model_name='arenacards',
            name='class_warlock',
        ),
        migrations.RemoveField(
            model_name='arenacards',
            name='class_warrior',
        ),
        migrations.AddField(
            model_name='arenacards',
            name='classification',
            field=models.CharField(blank=True, choices=[('ALL', '全部'), ('DRUID', '德鲁伊'), ('HUNTER', '猎人'), ('MAGE', '法师'), ('PALADIN', '圣骑士'), ('PRIEST', '牧师'), ('ROGUE', '潜行者'), ('SHAMAN', '萨满'), ('WARLOCK', '术士'), ('WARRIOR', '战士')], max_length=20, null=True, verbose_name='职业分类'),
        ),
        migrations.AddField(
            model_name='arenacards',
            name='copies',
            field=models.IntegerField(blank=True, null=True, verbose_name='张数'),
        ),
        migrations.AddField(
            model_name='arenacards',
            name='deck_pop',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='套牌中出现概率'),
        ),
        migrations.AddField(
            model_name='arenacards',
            name='deck_winrate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='卡组胜率'),
        ),
        migrations.AddField(
            model_name='arenacards',
            name='played_pop',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='打出卡牌中占比'),
        ),
        migrations.AddField(
            model_name='arenacards',
            name='played_winrate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='打出胜率'),
        ),
        migrations.AddField(
            model_name='arenacards',
            name='times_played',
            field=models.IntegerField(blank=True, null=True, verbose_name='打出次数'),
        ),
    ]
