# Generated by Django 2.0.4 on 2018-12-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0027_auto_20181212_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='arenacards',
            name='ifanId',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ifanId'),
        ),
    ]
