# Generated by Django 2.0.4 on 2019-02-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0032_arenacards_stdev'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arenacards',
            old_name='stdev',
            new_name='deck_pop_stdev',
        ),
        migrations.AddField(
            model_name='arenacards',
            name='deck_pop_mean',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='出现率均值'),
        ),
    ]
