# Generated by Django 2.0.4 on 2019-03-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0033_auto_20190226_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscards',
            name='img_card_link',
            field=models.TextField(blank=True, null=True, verbose_name='card图片地址'),
        ),
        migrations.AddField(
            model_name='hscards',
            name='img_tile_link',
            field=models.TextField(blank=True, null=True, verbose_name='tile图片地址'),
        ),
        migrations.AlterField(
            model_name='arenacards',
            name='deck_pop_mean',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='出现率均值'),
        ),
        migrations.AlterField(
            model_name='arenacards',
            name='deck_pop_stdev',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='出现率标准差'),
        ),
    ]
