# Generated by Django 2.0.4 on 2019-04-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0034_auto_20190304_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='arenacards',
            name='img_tile_link',
            field=models.TextField(blank=True, null=True, verbose_name='tile图片地址'),
        ),
    ]
