# Generated by Django 2.0.4 on 2019-06-19 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0035_arenacards_img_tile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscards',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
