# Generated by Django 2.0.4 on 2019-06-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0036_hscards_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hscards',
            old_name='create_time',
            new_name='update_time',
        ),
    ]
