# Generated by Django 2.0.4 on 2019-06-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0038_auto_20190619_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscards',
            name='entourage',
            field=models.TextField(blank=True, null=True, verbose_name='衍生卡'),
        ),
    ]
