# Generated by Django 2.0.4 on 2019-06-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0040_hscards_invalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenacards',
            name='rarity',
            field=models.CharField(blank=True, choices=[('FREE', '免费'), ('COMMON', '普通'), ('RARE', '稀有'), ('EPIC', '史诗'), ('LEGENDARY', '传说')], max_length=20, null=True, verbose_name='稀有度'),
        ),
    ]
