# Generated by Django 2.0.4 on 2019-11-05 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0041_auto_20190623_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSBattleGroundCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsId', models.CharField(blank=True, max_length=20, null=True, verbose_name='hsId')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('entourageID', models.TextField(blank=True, null=True, verbose_name='衍生卡')),
                ('upgradeID', models.IntegerField(blank=True, null=True, verbose_name='三连卡牌')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='费用')),
                ('attack', models.IntegerField(blank=True, null=True, verbose_name='攻击力')),
                ('health', models.IntegerField(blank=True, null=True, verbose_name='血量')),
                ('tier', models.IntegerField(blank=True, null=True, verbose_name='等级')),
                ('hero', models.BooleanField(verbose_name='是否为英雄卡')),
                ('minionType', models.CharField(blank=True, choices=[('14', '鱼人'), ('15', '恶魔'), ('17', '机械'), ('20', '野兽'), ('26', '全部')], max_length=20, null=True, verbose_name='随从种类')),
                ('rarityID', models.IntegerField(blank=True, null=True, verbose_name='稀有度')),
                ('setID', models.IntegerField(blank=True, null=True, verbose_name='扩展包ID')),
                ('typeID', models.IntegerField(blank=True, null=True, verbose_name='类型ID')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='关键词')),
                ('flavor', models.TextField(blank=True, null=True, verbose_name='背景')),
                ('text', models.TextField(blank=True, null=True, verbose_name='效果')),
                ('artist', models.CharField(blank=True, max_length=200, null=True, verbose_name='艺术家')),
                ('collectible', models.BooleanField(verbose_name='可收集')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '卡牌详情',
                'verbose_name_plural': '卡牌详情',
            },
        ),
    ]
