# Generated by Django 2.0.4 on 2019-11-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0044_hsbattlegroundcards_parentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsbattlegroundcards',
            name='outTier',
            field=models.IntegerField(blank=True, null=True, verbose_name='外部等级'),
        ),
    ]
