# Generated by Django 2.0.4 on 2020-02-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0046_auto_20191105_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsbattlegroundcards',
            name='minionType',
            field=models.CharField(blank=True, choices=[('14', '鱼人'), ('15', '恶魔'), ('17', '机械'), ('20', '野兽'), ('24', '龙'), ('26', '全部')], max_length=20, null=True, verbose_name='随从种类'),
        ),
    ]
