# Generated by Django 2.0.4 on 2020-03-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0047_auto_20200227_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenacards',
            name='cardClass',
            field=models.CharField(blank=True, choices=[('Druid', '德鲁伊'), ('Hunter', '猎人'), ('Mage', '法师'), ('Paladin', '圣骑士'), ('Priest', '牧师'), ('Rogue', '潜行者'), ('Shaman', '萨满'), ('Warlock', '术士'), ('Warrior', '战士'), ('DemonHunter', '恶魔猎手'), ('Neutral', '中立')], max_length=20, null=True, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='arenacards',
            name='classification',
            field=models.CharField(blank=True, choices=[('ALL', '全部'), ('DRUID', '德鲁伊'), ('HUNTER', '猎人'), ('MAGE', '法师'), ('PALADIN', '圣骑士'), ('PRIEST', '牧师'), ('ROGUE', '潜行者'), ('SHAMAN', '萨满'), ('WARLOCK', '术士'), ('WARRIOR', '战士'), ('DEMONHUNTER', '恶魔猎手')], max_length=20, null=True, verbose_name='职业分类'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='faction',
            field=models.CharField(blank=True, choices=[('Druid', '德鲁伊'), ('Hunter', '猎人'), ('Mage', '法师'), ('Paladin', '圣骑士'), ('Priest', '牧师'), ('Rogue', '潜行者'), ('Shaman', '萨满'), ('Warlock', '术士'), ('Warrior', '战士'), ('DemonHunter', '恶魔猎手'), ('Neutral', '中立')], max_length=20, null=True, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='hscards',
            name='cardClass',
            field=models.CharField(blank=True, choices=[('Druid', '德鲁伊'), ('Hunter', '猎人'), ('Mage', '法师'), ('Paladin', '圣骑士'), ('Priest', '牧师'), ('Rogue', '潜行者'), ('Shaman', '萨满'), ('Warlock', '术士'), ('Warrior', '战士'), ('DemonHunter', '恶魔猎手'), ('Neutral', '中立')], max_length=20, null=True, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='series',
            name='ename',
            field=models.CharField(default='', max_length=100, verbose_name='扩展包（英文）'),
        ),
    ]
