# Generated by Django 2.0.4 on 2020-05-14 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0050_auto_20200410_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscards',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
    ]
