# Generated by Django 2.0.4 on 2020-08-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0053_auto_20200807_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hscards',
            old_name='classes',
            new_name='multiClass',
        ),
    ]
