# Generated by Django 2.0.4 on 2020-08-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0054_auto_20200807_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hscards',
            old_name='multiClass',
            new_name='classes',
        ),
    ]
