# Generated by Django 2.2 on 2021-03-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0055_auto_20200807_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscards',
            name='howToEarn',
            field=models.TextField(blank=True, null=True, verbose_name='如何获取'),
        ),
        migrations.AddField(
            model_name='hscards',
            name='howToEarnGolden',
            field=models.TextField(blank=True, null=True, verbose_name='如何获取（金卡）'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='mode',
            field=models.CharField(blank=True, choices=[('All', '全部模式'), ('Classic', '经典模式'), ('Standard', '标准模式'), ('Wild', '狂野模式'), ('Arena', '竞技场'), ('Duels', '对决模式')], help_text='游戏模式', max_length=20, null=True, verbose_name='游戏模式'),
        ),
        migrations.AlterField(
            model_name='series',
            name='mode',
            field=models.CharField(blank=True, choices=[('All', '全部模式'), ('Classic', '经典模式'), ('Standard', '标准模式'), ('Wild', '狂野模式'), ('Arena', '竞技场'), ('Duels', '对决模式')], help_text='游戏模式', max_length=20, null=True, verbose_name='游戏模式'),
        ),
    ]
