# Generated by Django 2.2 on 2022-01-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0056_auto_20210327_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsbattlegroundcards',
            name='companionId',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='同伴卡'),
        ),
    ]
