# Generated by Django 2.0.4 on 2018-08-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winrate', '0004_auto_20180824_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hswinrate',
            name='popularity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='热度'),
        ),
        migrations.AlterField(
            model_name='hswinrate',
            name='winrate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='胜率'),
        ),
    ]
