# Generated by Django 2.0.4 on 2018-09-17 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winrate', '0007_decknametranslate'),
    ]

    operations = [
        migrations.AddField(
            model_name='decknametranslate',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='日期'),
        ),
    ]
