# Generated by Django 2.0.4 on 2018-11-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winrate', '0008_decknametranslate_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hswinrate',
            name='best_deck',
            field=models.TextField(blank=True, default='', null=True, verbose_name='最优异卡组'),
        ),
        migrations.AddField(
            model_name='hswinrate',
            name='best_matchup',
            field=models.TextField(blank=True, default='', null=True, verbose_name='最优对局'),
        ),
        migrations.AddField(
            model_name='hswinrate',
            name='core_cards',
            field=models.TextField(blank=True, default='', null=True, verbose_name='核心卡牌'),
        ),
        migrations.AddField(
            model_name='hswinrate',
            name='faction_popularity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='职业占比'),
        ),
        migrations.AddField(
            model_name='hswinrate',
            name='matchup',
            field=models.TextField(blank=True, default='', null=True, verbose_name='对抗情况'),
        ),
        migrations.AddField(
            model_name='hswinrate',
            name='pop_cards',
            field=models.TextField(blank=True, default='', null=True, verbose_name='热门卡牌'),
        ),
        migrations.AddField(
            model_name='hswinrate',
            name='pop_deck',
            field=models.TextField(blank=True, default='', null=True, verbose_name='最受欢迎卡组'),
        ),
        migrations.AddField(
            model_name='hswinrate',
            name='worst_matchup',
            field=models.TextField(blank=True, default='', null=True, verbose_name='最劣对局'),
        ),
    ]
