# Generated by Django 2.0.4 on 2018-11-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winrate', '0009_auto_20181101_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='hswinrate',
            name='real_games',
            field=models.IntegerField(blank=True, null=True, verbose_name='完整对局数'),
        ),
        migrations.AddField(
            model_name='hswinrate',
            name='real_winrate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='完整胜率'),
        ),
    ]
