# Generated by Django 2.0.4 on 2019-02-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winrate', '0010_auto_20181101_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='hswinrate',
            name='rank_range',
            field=models.CharField(choices=[('All', '全分段'), ('Legend_Only', '传说分段'), ('One_Through_Five', '5级-1级分段')], default='All', max_length=200, verbose_name='排名分段'),
        ),
    ]
