# Generated by Django 2.0.4 on 2020-04-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winrate', '0013_auto_20200330_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hswinrate',
            name='rank_range',
            field=models.CharField(choices=[('BRONZE_TO_GOLD', '青铜-黄金'), ('PLATINUM_TO_LEGEND', '白金-传说'), ('Legend', '传说')], default='All', max_length=200, verbose_name='排名分段'),
        ),
    ]
