# Generated by Django 2.0.4 on 2020-04-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winrate', '0021_auto_20200429_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hswinrate',
            name='rank_range',
            field=models.CharField(choices=[('All', '全分段'), ('Legend_Only', '传说分段（旧）'), ('One_Through_Five', '5级-1级分段'), ('Six_Through_Ten', '10级-6级分段'), ('BRONZE_THROUGH_GOLD', '青铜-黄金'), ('DIAMOND_THROUGH_LEGEND', '钻石-传说'), ('DIAMOND_FOUR_THROUGH_DIAMOND_ONE', '钻4-钻1'), ('LEGEND', '传说'), ('TOP_1000_LEGEND', '传说Top1000')], default='BRONZE_THROUGH_GOLD', max_length=200, verbose_name='排名分段'),
        ),
    ]
