# Generated by Django 2.2 on 2022-06-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winrate', '0022_auto_20200430_1203'),
        ('winrate', '0012_auto_20201215_1604'),
    ]

    operations = [
    ]
