# Generated by Django 2.2 on 2020-12-15 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winrate', '0022_auto_20200430_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='hswinrate',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='hswinrate',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加日期'),
        ),
    ]
