# Generated by Django 2.2 on 2020-12-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winrate', '0012_auto_20201215_1604'),
        ('winrate', '0023_auto_20201215_1600'),
    ]

    operations = [
    ]
