# Generated by Django 2.0.4 on 2018-08-21 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(blank=True, max_length=20, null=True, verbose_name='梯队')),
                ('faction', models.CharField(blank=True, choices=[('Druid', '德鲁伊'), ('Hunter', '猎人'), ('Mage', '法师'), ('Paladin', '圣骑士'), ('Priest', '牧师'), ('Rogue', '潜行者'), ('Shaman', '萨满'), ('Warlock', '术士'), ('Warrior', '战士'), ('Neutral', '中立')], max_length=20, null=True, verbose_name='职业')),
                ('archetype_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='牌组名称')),
                ('win_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='胜率')),
                ('game_count', models.IntegerField(blank=True, null=True, verbose_name='总对局数')),
                ('popularity', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='热度')),
                ('best_matchup', models.TextField(blank=True, default='', null=True, verbose_name='最优对局')),
                ('worst_matchup', models.TextField(blank=True, default='', null=True, verbose_name='最劣对局')),
                ('core_cards', models.TextField(blank=True, default='', null=True, verbose_name='核心卡牌')),
                ('pop_cards', models.TextField(blank=True, default='', null=True, verbose_name='热门卡牌')),
                ('matchup', models.TextField(blank=True, default='', null=True, verbose_name='对抗情况')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '卡组模板数据',
                'verbose_name_plural': '卡组模板数据',
            },
        ),
    ]
