# Generated by Django 2.0.4 on 2018-08-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archetype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archetype',
            name='archetype_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='牌组名称'),
        ),
    ]
