# Generated by Django 2.0.4 on 2018-08-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archetype', '0002_auto_20180824_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archetype',
            name='popularity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='热度'),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='win_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='胜率'),
        ),
    ]
