# Generated by Django 2.0.4 on 2018-10-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archetype', '0005_auto_20180824_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='archetype',
            name='best_deck',
            field=models.TextField(blank=True, default='', null=True, verbose_name='最优异卡组'),
        ),
        migrations.AddField(
            model_name='archetype',
            name='pop_deck',
            field=models.TextField(blank=True, default='', null=True, verbose_name='最受欢迎卡组'),
        ),
    ]
