# Generated by Django 2.0.4 on 2019-02-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archetype', '0006_auto_20181015_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='archetype',
            name='rank_range',
            field=models.CharField(default='All', max_length=200, verbose_name='排名分段'),
        ),
    ]
