# Generated by Django 2.0.4 on 2019-03-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archetype', '0008_auto_20190217_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='archetype',
            name='popularity1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='热度'),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='popularity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='职业内占比'),
        ),
    ]
