# Generated by Django 2.0.4 on 2019-09-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archetype', '0009_auto_20190315_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archetype',
            name='rank_range',
            field=models.CharField(choices=[('All', '全分段'), ('Legend_Only', '传说分段'), ('One_Through_Five', '5级-1级分段'), ('Six_Through_Ten', '10级-6级分段')], default='All', max_length=200, verbose_name='排名分段'),
        ),
    ]
