# Generated by Django 2.2 on 2022-06-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archetype', '0020_auto_20200430_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archetype',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
